steps:
- name: 'gcr.io/cloud-builders/wget'
  args:
  - '--quiet'
  - '-O'
  - 'firebase'
  - 'https://firebase.tools/bin/linux/latest'
 

- name: 'ubuntu:18.04'
  args:
  - 'bash'
  - '-c'
  - |
    apt-get update
    apt-get install -y git
    mv firebase /tmp

    git clone https://github.com/cballenar/animated-illustrations.git ./public/animated-illustrations
    git clone https://github.com/cballenar/badass.git ./public/badass
    git clone https://github.com/cballenar/base12.git ./public/base12
    git clone https://github.com/cballenar/blob.git ./public/blob
    git clone https://github.com/cballenar/crnch-it.git ./public/crnch-it
    git clone https://github.com/cballenar/crunchypaste.git ./public/crunchypaste
    git clone https://github.com/cballenar/dagrid.git ./public/dagrid
    git clone https://github.com/cballenar/emzy.git ./public/emzy
    git clone https://github.com/cballenar/numeros.git ./public/numeros
    git clone https://github.com/cballenar/sketchyweb.git ./public/sketchyweb

    chmod 755 /tmp/firebase
    /tmp/firebase deploy --project ${PROJECT_ID} --non-interactive --only hosting -m "Build ${BUILD_ID}"
 
