steps:
- name: 'gcr.io/cloud-builders/wget'
  args:
  - '--quiet'
  - '-O'
  - 'firebase'
  - 'https://firebase.tools/bin/linux/latest'
 

- name: 'ubuntu:18.04'
  args:
  - 'bash'
  - '-c'
  - |
    apt-get update
    apt-get install -y git
    mv firebase /tmp

    git clone git@github.com:cballenar/animated-illustrations.git ./public/animated-illustrations

    chmod 755 /tmp/firebase
    /tmp/firebase deploy --project ${PROJECT_ID} --non-interactive --only hosting -m "Build ${BUILD_ID}"
 
